<?php
    /** @var Prymag\CookieNotice\Block\Widget\AllowCookieButton $block */
?>
<div class="actions">
    <button id="prymag-btn-cookie-allow" class="action allow primary">
        <span><?= $block->getData('btn_label') ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#notice-cookie-block": {
            "cookieNotices": {
                "cookieAllowButtonSelector": "#prymag-btn-cookie-allow",
                "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
            }
        }
    }
</script>